version: '2.2'
services:
  web_#{REPOSITORYNAME}#:
    image: #{IMAGETAG}#
    ports:
      - "4005:8080"
    restart: always
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.192.0/24